defmodule Flashwars.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      modify :state, :map, null: false, default: nil
    end
  end

  def down do
    alter table(:sessions) do
      modify :state, :map, null: true, default: %{}
    end
  end
end
