defmodule Flashwars.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_stats, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :xp, :bigint, default: 0
      add :level, :bigint, default: 1
      add :streak, :bigint, default: 0
      add :longest_streak, :bigint, default: 0
      add :last_round_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_stats_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "user_stats_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:user_stats, [:user_id, :organization_id],
             name: "user_stats_by_user_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_stats, [:user_id, :organization_id],
                     name: "user_stats_by_user_org_index"
                   )

    drop constraint(:user_stats, "user_stats_user_id_fkey")

    drop constraint(:user_stats, "user_stats_organization_id_fkey")

    drop table(:user_stats)
  end
end
