defmodule Flashwars.Repo.Migrations.TermDistractorsField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:terms) do
      add :distractors, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:terms) do
      remove :distractors
    end
  end
end
