defmodule Flashwars.Repo.Migrations.ContentTagsAndSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tags, [:name], name: "tags_unique_name_index")

    create table(:set_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :study_set_id,
          references(:study_sets,
            column: :id,
            name: "set_tags_study_set_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "set_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:set_tags, [:study_set_id, :tag_id], name: "set_tags_unique_pair_index")

    create table(:sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mode, :text, null: false
      add :state, :map, default: %{}
      add :last_saved_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "sessions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :study_set_id,
          references(:study_sets,
            column: :id,
            name: "sessions_study_set_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:sessions, [:user_id, :study_set_id, :mode],
             name: "sessions_by_user_set_mode_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sessions, [:user_id, :study_set_id, :mode],
                     name: "sessions_by_user_set_mode_index"
                   )

    drop constraint(:sessions, "sessions_user_id_fkey")

    drop constraint(:sessions, "sessions_study_set_id_fkey")

    drop table(:sessions)

    drop_if_exists unique_index(:set_tags, [:study_set_id, :tag_id],
                     name: "set_tags_unique_pair_index"
                   )

    drop constraint(:set_tags, "set_tags_study_set_id_fkey")

    drop constraint(:set_tags, "set_tags_tag_id_fkey")

    drop table(:set_tags)

    drop_if_exists unique_index(:tags, [:name], name: "tags_unique_name_index")

    drop table(:tags)
  end
end
