defmodule Flashwars.Repo.Migrations.DomainsInitial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :class_id, :uuid, null: false
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:study_sets) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "study_sets_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:study_sets, [:organization_id])

    alter table(:organizations) do
      add :name, :text, null: false
      add :support_contact, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:org_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "member"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "org_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "org_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:org_memberships, [:organization_id, :user_id],
             name: "org_memberships_unique_member_index"
           )

    create table(:org_domains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :domain, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "org_domains_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:org_domains, [:organization_id, :domain],
             name: "org_domains_unique_org_domain_index"
           )

    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :data, :map, default: %{}
      add :read_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:leaderboard_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope, :text
      add :mode, :text, default: "game"
      add :score, :bigint, null: false
      add :submitted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "leaderboard_entries_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :study_set_id,
          references(:study_sets,
            column: :id,
            name: "leaderboard_entries_study_set_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:leaderboard_entries, [:scope, :mode, :user_id],
             name: "leaderboard_entries_unique_scope_user_index"
           )

    create table(:game_submissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :answer, :text
      add :correct, :boolean, default: false
      add :score, :bigint, default: 0
      add :submitted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_room_id, :uuid, null: false
      add :game_round_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:game_rounds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :number, :bigint, null: false
      add :state, :text, default: "question"
      add :question_data, :map, default: %{}
      add :started_at, :utc_datetime
      add :ended_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_room_id, :uuid, null: false
    end

    create table(:game_rooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:game_submissions) do
      modify :game_room_id,
             references(:game_rooms,
               column: :id,
               name: "game_submissions_game_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :game_round_id,
             references(:game_rounds,
               column: :id,
               name: "game_submissions_game_round_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "game_submissions_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:game_submissions, [:game_round_id, :user_id],
             name: "game_submissions_one_submission_per_round_index"
           )

    alter table(:game_rounds) do
      modify :game_room_id,
             references(:game_rooms,
               column: :id,
               name: "game_rounds_game_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:game_rooms) do
      add :type, :text
      add :state, :text, default: "lobby"
      add :config, :map, default: %{}
      add :rating_scope, :text

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "game_rooms_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :started_at, :utc_datetime
      add :ended_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :host_id,
          references(:users,
            column: :id,
            name: "game_rooms_host_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :study_set_id,
          references(:study_sets,
            column: :id,
            name: "game_rooms_study_set_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:enrollments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "student"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :section_id,
          references(:sections,
            column: :id,
            name: "enrollments_section_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "enrollments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:enrollments, [:section_id, :user_id],
             name: "enrollments_unique_enrollment_index"
           )

    create table(:classes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sections) do
      modify :class_id,
             references(:classes,
               column: :id,
               name: "sections_class_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:classes) do
      add :name, :text, null: false
      add :description, :text

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "classes_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :resource, :text, null: false
      add :resource_id, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "audit_logs_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mode, :text, default: "test"
      add :score, :bigint, default: 0
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "attempts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :study_set_id,
          references(:study_sets,
            column: :id,
            name: "attempts_study_set_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :assignment_id, :uuid
    end

    create table(:attempt_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :answer, :text
      add :correct, :boolean, default: false
      add :score, :bigint, default: 0
      add :evaluated_at, :utc_datetime
      add :ai_confidence, :float
      add :ai_explanation, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :attempt_id,
          references(:attempts,
            column: :id,
            name: "attempt_items_attempt_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :term_id,
          references(:terms,
            column: :id,
            name: "attempt_items_term_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:attempts) do
      modify :assignment_id,
             references(:assignments,
               column: :id,
               name: "attempts_assignment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:assignments) do
      add :mode, :text, default: "test"
      add :due_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :section_id,
          references(:sections,
            column: :id,
            name: "assignments_section_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :study_set_id,
          references(:study_sets,
            column: :id,
            name: "assignments_study_set_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:assignments, "assignments_section_id_fkey")

    drop constraint(:assignments, "assignments_study_set_id_fkey")

    alter table(:assignments) do
      remove :study_set_id
      remove :section_id
      remove :updated_at
      remove :inserted_at
      remove :due_at
      remove :mode
    end

    drop constraint(:attempts, "attempts_assignment_id_fkey")

    alter table(:attempts) do
      modify :assignment_id, :uuid
    end

    drop table(:assignments)

    drop constraint(:attempt_items, "attempt_items_attempt_id_fkey")

    drop constraint(:attempt_items, "attempt_items_term_id_fkey")

    drop table(:attempt_items)

    drop constraint(:attempts, "attempts_user_id_fkey")

    drop constraint(:attempts, "attempts_study_set_id_fkey")

    drop table(:attempts)

    drop constraint(:audit_logs, "audit_logs_actor_id_fkey")

    drop table(:audit_logs)

    drop constraint(:classes, "classes_organization_id_fkey")

    alter table(:classes) do
      remove :updated_at
      remove :inserted_at
      remove :organization_id
      remove :description
      remove :name
    end

    drop constraint(:sections, "sections_class_id_fkey")

    alter table(:sections) do
      modify :class_id, :uuid
    end

    drop table(:classes)

    drop_if_exists unique_index(:enrollments, [:section_id, :user_id],
                     name: "enrollments_unique_enrollment_index"
                   )

    drop constraint(:enrollments, "enrollments_section_id_fkey")

    drop constraint(:enrollments, "enrollments_user_id_fkey")

    drop table(:enrollments)

    drop constraint(:game_rooms, "game_rooms_organization_id_fkey")

    drop constraint(:game_rooms, "game_rooms_host_id_fkey")

    drop constraint(:game_rooms, "game_rooms_study_set_id_fkey")

    alter table(:game_rooms) do
      remove :study_set_id
      remove :host_id
      remove :updated_at
      remove :inserted_at
      remove :ended_at
      remove :started_at
      remove :organization_id
      remove :rating_scope
      remove :config
      remove :state
      remove :type
    end

    drop constraint(:game_rounds, "game_rounds_game_room_id_fkey")

    alter table(:game_rounds) do
      modify :game_room_id, :uuid
    end

    drop_if_exists unique_index(:game_submissions, [:game_round_id, :user_id],
                     name: "game_submissions_one_submission_per_round_index"
                   )

    drop constraint(:game_submissions, "game_submissions_game_room_id_fkey")

    drop constraint(:game_submissions, "game_submissions_game_round_id_fkey")

    drop constraint(:game_submissions, "game_submissions_user_id_fkey")

    alter table(:game_submissions) do
      modify :user_id, :uuid
      modify :game_round_id, :uuid
      modify :game_room_id, :uuid
    end

    drop table(:game_rooms)

    drop table(:game_rounds)

    drop table(:game_submissions)

    drop_if_exists unique_index(:leaderboard_entries, [:scope, :mode, :user_id],
                     name: "leaderboard_entries_unique_scope_user_index"
                   )

    drop constraint(:leaderboard_entries, "leaderboard_entries_user_id_fkey")

    drop constraint(:leaderboard_entries, "leaderboard_entries_study_set_id_fkey")

    drop table(:leaderboard_entries)

    drop constraint(:notifications, "notifications_user_id_fkey")

    drop table(:notifications)

    drop_if_exists unique_index(:org_domains, [:organization_id, :domain],
                     name: "org_domains_unique_org_domain_index"
                   )

    drop constraint(:org_domains, "org_domains_organization_id_fkey")

    drop table(:org_domains)

    drop_if_exists unique_index(:org_memberships, [:organization_id, :user_id],
                     name: "org_memberships_unique_member_index"
                   )

    drop constraint(:org_memberships, "org_memberships_organization_id_fkey")

    drop constraint(:org_memberships, "org_memberships_user_id_fkey")

    drop table(:org_memberships)

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :support_contact
      remove :name
    end

    drop_if_exists index(:study_sets, [:organization_id])

    drop constraint(:study_sets, "study_sets_organization_id_fkey")

    alter table(:study_sets) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop table(:sections)
  end
end
