defmodule Flashwars.Repo.Migrations.AddOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:tags, [:name], name: "tags_unique_name_index")

    create unique_index(:tags, [:organization_id, :name], name: "tags_unique_name_per_org_index")
  end

  def down do
    drop_if_exists unique_index(:tags, [:organization_id, :name],
                     name: "tags_unique_name_per_org_index"
                   )

    create unique_index(:tags, [:name], name: "tags_unique_name_index")
  end
end
