defmodule Flashwars.Repo.Migrations.AddGamePrivateLink do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_rooms) do
      add :privacy, :text, default: "private"
      add :link_token, :text
    end
  end

  def down do
    alter table(:game_rooms) do
      remove :link_token
      remove :privacy
    end
  end
end
