defmodule Flashwars.Repo.Migrations.LearningSchedulerV1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:card_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stability_days, :float, default: 0.3
      add :difficulty, :float, default: 6.0
      add :prev_interval_days, :float, default: 0.0
      add :streak, :bigint, default: 0
      add :lapses, :bigint, default: 0
      add :relearn_stage, :bigint, default: 0
      add :t_last, :utc_datetime
      add :next_due_at, :utc_datetime
      add :last_rt_ms, :bigint
      add :last_conf, :bigint

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "card_states_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "card_states_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :term_id,
          references(:terms,
            column: :id,
            name: "card_states_term_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :study_set_id,
          references(:study_sets,
            column: :id,
            name: "card_states_study_set_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:card_states, [:user_id, :term_id],
             name: "card_states_by_user_term_index"
           )

    alter table(:attempt_items) do
      add :grade, :text
      add :response_time_ms, :bigint
      add :confidence, :bigint
      add :prev_interval_days, :float
      add :next_interval_days, :float
      add :s_before, :float
      add :s_after, :float
      add :d_before, :float
      add :d_after, :float
      add :queue_type, :text
      add :app_version, :text
      add :device, :text
    end
  end

  def down do
    alter table(:attempt_items) do
      remove :device
      remove :app_version
      remove :queue_type
      remove :d_after
      remove :d_before
      remove :s_after
      remove :s_before
      remove :next_interval_days
      remove :prev_interval_days
      remove :confidence
      remove :response_time_ms
      remove :grade
    end

    drop_if_exists unique_index(:card_states, [:user_id, :term_id],
                     name: "card_states_by_user_term_index"
                   )

    drop constraint(:card_states, "card_states_organization_id_fkey")

    drop constraint(:card_states, "card_states_user_id_fkey")

    drop constraint(:card_states, "card_states_term_id_fkey")

    drop constraint(:card_states, "card_states_study_set_id_fkey")

    drop table(:card_states)
  end
end
