defmodule Flashwars.Repo.Migrations.ContentTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:terms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :term, :text, null: false
      add :definition, :text, null: false
      add :position, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :study_set_id, :uuid, null: false
    end

    create table(:study_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:terms) do
      modify :study_set_id,
             references(:study_sets,
               column: :id,
               name: "terms_study_set_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:study_sets) do
      add :name, :text, null: false
      add :description, :text
      add :privacy, :text, default: "private"
      add :tags_cache, {:array, :text}, default: []
      add :link_token, :text
      add :organization_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "study_sets_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :folder_id, :uuid
      add :archived_at, :utc_datetime_usec
    end

    create table(:folders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:study_sets) do
      modify :folder_id,
             references(:folders,
               column: :id,
               name: "study_sets_folder_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:study_sets, [:owner_id, :name], name: "study_sets_owner_name_index")

    alter table(:folders) do
      add :name, :text, null: false
      add :organization_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "folders_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:folders, "folders_owner_id_fkey")

    alter table(:folders) do
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :organization_id
      remove :name
    end

    drop_if_exists unique_index(:study_sets, [:owner_id, :name],
                     name: "study_sets_owner_name_index"
                   )

    drop constraint(:study_sets, "study_sets_folder_id_fkey")

    alter table(:study_sets) do
      modify :folder_id, :uuid
    end

    drop table(:folders)

    drop constraint(:study_sets, "study_sets_owner_id_fkey")

    alter table(:study_sets) do
      remove :archived_at
      remove :folder_id
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :organization_id
      remove :link_token
      remove :tags_cache
      remove :privacy
      remove :description
      remove :name
    end

    drop constraint(:terms, "terms_study_set_id_fkey")

    alter table(:terms) do
      modify :study_set_id, :uuid
    end

    drop table(:study_sets)

    drop table(:terms)
  end
end
