defmodule Flashwars.Repo.Migrations.ContentInitial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :site_admin, :boolean, default: false
      add :settings, :map, default: %{}
      add :last_login_at, :utc_datetime
    end
  end

  def down do
    alter table(:users) do
      remove :last_login_at
      remove :settings
      remove :site_admin
    end
  end
end
