defmodule Flashwars.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_submissions) do
      modify :score, :bigint, default: nil
    end
  end

  def down do
    alter table(:game_submissions) do
      modify :score, :bigint, default: 0
    end
  end
end
